# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6baba0075b9eb5c9ed435fa912f4cc22ebb1a1d8ee1edf8d72703b2b2daf6196f84395e90019bbeb9b8a5ba333a5c5c7d68acf5947f714fd0f6b6ecdbdd8c609

test:
  secret_key_base: b97c1c5909a61422e37a53e43f7d8354a79b99946d893f8f9ad31b536e2fe8eced3f4cc745f18f578bc6a3c20ddd8a1f60ee5231df61f6c230e3d62ba639357f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
